"""create user_preferences table

Revision ID: d03ab2f96996
Revises: 2a41ac3f8a3c
Create Date: 2026-08-11 10:54:15.411555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd03ab2f96996'
down_revision: Union[str, Sequence[str], None] = '2a41ac3f8a3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('food_preference', sa.Enum('VEGETARIAN', 'NON_VEGETARIAN', 'VEGAN', 'NO_PREFERENCE', name='foodpreference'), nullable=False),
    sa.Column('drinking_preference', sa.Enum('DRINKER', 'NON_DRINKER', 'NO_PREFERENCE', name='drinkingpreference'), nullable=False),
    sa.Column('travel_style', sa.Enum('ADVENTURE', 'RELAXED', 'CULTURAL', 'LUXURY', 'BUDGET', 'MIXED', name='travelstyle'), nullable=False),
    sa.Column('travel_pace', sa.Enum('RELAXED', 'MODERATE', 'PACKED', name='travelpace'), nullable=False),
    sa.Column('accommodation_preference', sa.Enum('HOTEL', 'HOSTEL', 'RESORT', 'HOMESTAY', 'NO_PREFERENCE', name='accommodationpreference'), nullable=False),
    sa.Column('interests', sa.String(length=500), nullable=False),
    sa.Column('additional_preferences', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
